com.griddynamics.es.graduation.project:
  esHost: http://localhost:9200
  user:
  pass:
  index: products-ship

  files:
    signals.mapping:  classpath:elastic/products/signals-mappings.json
    product-mappings: classpath:elastic/products/product-mappings.json
    settings: classpath:elastic/products/settings.json
    bulkData: classpath:elastic/products/products.ndjson
com:
  griddynamics:
    es:
      signals:
        index:
          product-signals
spring:
  application:
    name: clickstream-app
server:
  port: 8081
springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
