com.griddynamics.es.graduation.project:
  esHost: http://localhost:9200
  user:
  pass:
  index: wczet-products

  files:
    mappings: classpath:elastic/products/mappings.json
    settings: classpath:elastic/products/settings.json
    bulkData: classpath:elastic/products/product_catalog.ndjson

spring:
  application:
    name: product-indexer
