com.griddynamics.es.graduation.project:
  esHost: http://localhost:8200
  user:
  pass:
  index: typeaheads

  files:
    mappings: classpath:elastic/typeaheads/mappings.json
    settings: classpath:elastic/typeaheads/settings.json
    bulkData: classpath:elastic/typeaheads/bulk_data.txt

  request:
    default:
      findByQuerySize: 10
      getAllSize: 50
    minQueryLength: 3
    fuzziness:
      startsFromLength:
        one: 4
        two: 6
      boost:
        zero: 1.0
        one: 0.5
        two: 0.25
    prefixQueryBoost: 0.9