com.griddynamics.es.graduation.project:
  esHost: http://localhost:9200
  user:
  pass:
  index: products-capstone

  files:
    mappings: classpath:elastic/products/mappings.json
    settings: classpath:elastic/products/settings.json
    bulkData: classpath:elastic/products/data.txt

spring:
  application:
    name: product-indexer
