com.griddynamics.es.graduation.project:
  esHost: http://localhost:9200
  user:
  pass:
  index: wczet-blog-post-task1

  files:
    mappings: classpath:elastic/products/mappings.json
    settings: classpath:elastic/products/settings.json
    bulkData: classpath:elastic/products/blogs.ndjson

spring:
  application:
    name: task1-custom-analyzer
