com.griddynamics.es.graduation.project:
  esHost: http://localhost:9200
  user:
  pass:
  index: wczet-blog-post-baseline

  files:
    mappings: classpath:elastic/products/mappings-baseline.json
    settings: classpath:elastic/products/settings.json
    bulkData: classpath:elastic/products/blogs.ndjson

spring:
  application:
    name: task1-custom-analyzer
server:
  port: 8082
